server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

feign:
  httpclient:
    enabled: true

springdoc:
  packagesToScan: com.petto.posting