server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

com:
  petto:
    swagger2:
      gateway:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: petto-core-service
          uri: lb://petto-core-service
          predicates:
            - Path=/core/**
          filters:
            - RewritePath=/core/(?<path>.*), /$\{path}
        - id: petto-posting-service
          uri: lb://petto-posting-service
          predicates:
            - Path=/posting/**
          filters:
            - RewritePath=/posting/(?<path>.*), /$\{path}
        - id: petto-auth-service
          uri: lb://petto-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs